# Generated by Django 6.0.5 on 2026-06-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco_palette', '0003_remove_postphoto_photo_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AromaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='brand_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='cacao_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='chocolate_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='favorite_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='private_memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='tasting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='aroma_tags',
            field=models.ManyToManyField(blank=True, to='choco_palette.aromatag'),
        ),
        migrations.AddField(
            model_name='post',
            name='taste_tags',
            field=models.ManyToManyField(blank=True, to='choco_palette.tastetag'),
        ),
    ]
