# Generated by Django 6.0.5 on 2026-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choco_palette', '0007_profile_bio_alter_post_status_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
