# Generated by Django 6.0.5 on 2026-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco_palette', '0008_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
