# Generated by Django 6.0.5 on 2026-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco_palette', '0009_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, '下書き'), (1, '公開'), (2, '非公開')], default=0),
        ),
    ]
